### ISSUE TITLE
Compilation of tools with Visual Studio 2015 does not work; Configuration is in bad shape

### ISSUE THREAD

**Issue by goodidea82** [aap/librwgta#3]
1. I have successfully compiled the other project "librw" using all configurations Debug/Release and Win32/64bit using Visual Studio.
2. By reading the project configurations I figured out that the two projects should be in sibbling folders:
"librw" and "librwgta", which I did.
3. I have successfully compiled "librwgta.lib" using both configuration Debug x86 and x64 (Note the different configuration names from step 1).
4. Compilation of the project "convdff" fails with the following Linker errors (Debug x86 or x64):

Error LNK2019	The linker could not find a definition for external symbol ""public: void __cdecl rw::Geometry::buildTristrips(void)" (?buildTristrips@Geometry@rw@@QEAAXXZ)" in Funktion ""public: void __cdecl rw::Geometry::buildMeshes(void)" (?buildMeshes@Geometry@rw@@QEAAXXZ)".	convdff	C:\Games\GTA_SA\GTA_SA_ModdingTools\DFF_convdff_librw\librwgta\tools\convdff\librw.lib(geometry.obj)

Error LNK2019	The linker could not find a definition for external symbol  ""public: void __cdecl rw::BBox::calculate(struct rw::V3d *,int)" (?calculate@BBox@rw@@QEAAXPEAUV3d@2@H@Z)" in Funktion ""void __cdecl rw::cameraSync(struct rw::ObjectWithFrame *)" (?cameraSync@rw@@YAXPEAUObjectWithFrame@1@@Z)".	convdff	C:\Games\GTA_SA\GTA_SA_ModdingTools\DFF_convdff_librw\librwgta\tools\convdff\librw.lib(camera.obj)	

------------------------------
Btw, the project configuration is in bad shape. I could not configure the library and included paths by configuring the "librw Configuration->Path to libwr SDK" path. The path appears in the VC++ Directories but it does not appear in the final C/C++ command line. It gets lost somewhere. Same for the linker. Hence, I did what I described in step 2: I have name the folders and put them where they are expected. It would be great if you move the librw and librwgta projects to different places on your computer and fix the configuration problems that will show up.

**Comment by quiret** [comment]
"I could not configure the library and included paths by configuring the "librw Configuration->Path to libwr SDK" path."
But could you please at least say what you tried to put into the field? :-) It is always helpful to know. A screenshot would be most appreciated!

The linker errors come because the MSVC project configuration was not kept up-to-date with new source files. A typical scenario where this happens is when developers compile on an OS where MSVC does not run.

Aap, could you please add me as contributor to librw and librwgta so I can help you with maintenance? ;)

**Comment by aap** [comment]
I can do that, but let's think about how the project should be built. Right now i hacked together a bunch of makefiles that i'm not insanely happy with. The visual studio projects are also not the best. So I'm wondering whether we should autogenerate them (e.g. premake, cmake, autotools &c) or maintain them separately in the hope that we can keep things portable. What are your thoughts?

**Comment by quiret** [comment]
Autogeneration would revert the MSVC feature of path specification in project settings that I want to maintain. It could work if you document Environment Variables that everyone has to set for compilation. I guess it is easier to maintain automatically generated project files.

**Comment by goodidea82** [comment]
@quiret
> "I could not configure the library and included paths by configuring the "librw Configuration->Path to libwr SDK" path." But could you please at least say what you tried to put into the field? :-) It is always helpful to know. A screenshot would be most appreciated!

In my old configuration (before I did step 2) I have set LIBRWSDK_PATH= C:\Games\GTA_SA\GTA_SA_ModdingTools\DFF_convdff_librw\librw-master\librw 
The compiler or linker could not find the path to the library (because the LIBRWSDK_PATH variable is not consequently used I think). Then I have fixed in the problem by doing step 2. 
Here is the screenshot of my directory structure: http://imgur.com/a/9I98a
And here is the screenshot of the configuration (original configure): http://imgur.com/a/5mKn4
The compiled librw.lib is found, but I get the linker errors that I have reported about. (I.e., the path variable is perhaps not the issue I think)

**Comment by quiret** [comment]
@goodiea82 Have you tried compiling 'librw' again? I have fixed this problem there.

**Comment by goodidea82** [comment]
I have now checked out the latest versions of librw and librwgta. Again the folders are called librw and librwgta and are sibblings, so I do not modify any paths. In following I use the configuration "Debug x86"
-librw (compiles)
-librwgta (compiles)
- coltest (compiles)
- convdff (compiles now!!! :-) )
- convtxd (compiles)
- d3d9test (ERRORS C2039 and C2065) 
- IIItest (endless list of ERRORS)
- storiesconv (compiles)

(sorry it's German, but you can tell the location in the files. I have translated the first two error)
------ d3d9test (ERRORS C2039 and C2065) -------
error 	C2065	"loadTextures": not declared identifier	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	22	
error	  C2039	"currentTexDictionary": is not an element of "rw"	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	30	
Fehler	C2065	"currentTexDictionary": nichtdeklarierter Bezeichner	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	30	
Fehler	C2039	"currentTexDictionary": Ist kein Element von "rw"	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	49	
Fehler	C2065	"currentTexDictionary": nichtdeklarierter Bezeichner	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	49	
Fehler	C2039	"loadTextures": Ist kein Element von "rw"	d3d9test	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\d3d9test\d3dinit.cpp	22	

----- IIItest (endless list of ERRORS) -------
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	C3646	"ms_collisionInMemory": Unbekannter Überschreibungsspezifizierer	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\collision.h	4	
Fehler	C4430	Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\collision.h	4	
Fehler	C3646	"oldKeystates": Unbekannter Überschreibungsspezifizierer	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	79	
Fehler	C2143	Syntaxfehler: Es fehlt "," vor "["	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	79	
Fehler	C4430	Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	79	
Fehler	C3646	"newKeystates": Unbekannter Überschreibungsspezifizierer	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	80	
Fehler	C2143	Syntaxfehler: Es fehlt "," vor "["	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	80	
Fehler	C4430	Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	80	
Fehler	C3646	"tempKeystates": Unbekannter Überschreibungsspezifizierer	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	81	
Fehler	C2143	Syntaxfehler: Es fehlt "," vor "["	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	81	
Fehler	C4430	Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	81	
Fehler	C2143	Syntaxfehler: Es fehlt ")" vor ";"	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	84	
Fehler	C2059	Syntaxfehler: ")"	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	84	
Fehler	C2143	Syntaxfehler: Es fehlt ")" vor ";"	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	85	
Fehler	C2059	Syntaxfehler: ")"	IIItest	c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\iiitest\src\pad.h	85

**Comment by quiret** [comment]
@goodidea82 I have just fixed compilation of IIItest and d3d9test projects. You can now try compiling them yourself + consider contributing to the librwgta project ^^ Have fun!

**Comment by goodidea82** [comment]
I can confirm that all the VS projects compile. Great job guy!
Thanks for invitation to contribute.

**Comment by quiret** [comment]
We have switched compilation to premake. Points stated in this issue might not reflect the current codebase anymore :)
