### ISSUE TITLE
Compilation with Visual Studio does not work

### ISSUE THREAD

**Issue by goodidea82** [aap/librwgta#5]
I did the following:
1. checked-out of the project librwgta today
2. premak5 clean (just in case)
3. premake5 vs2015
5. opened build\librwgta.sln using Visual Studio 2015
6. tried to compile the project librwgta (configuration out of the box)
I get 4 times the following error message (translated from german):
C1083 Include file cannot be opened: "rw.h": No such file or directory

I did the same with librw and does compile successfully! 
The folders librw and librwgta are sibbling folders, i.e. the share the same parent folder, in case a cross reference is expected.

**Comment by aap** [comment]
Check the beginning of the premakefile, you have to set up some directories.

**Comment by goodidea82** [comment]
Setting the path to rw.h in the file premake5.lua solved the initial problem: the sub-project librwgta compiled successfully. I suggest to add these instructions to the readme.
I have set the following path: Librw = "C:/Games/GTA_SA/GTA_SA_ModdingTools/DFF_convdff_librw/librw"

However, now I get other problems. Compiling/linking the subproject coltest fails, because:
LNK1104 The file "rw.lib" cannot be opened.
I have checked, the file "rw.lib" does exist in "C:\Games\GTA_SA\GTA_SA_ModdingTools\DFF_convdff_librw\librw\lib\win-amd64-d3d9\Debug"

Another problem is reported here (translated to german):
1>c:\games\gta_sa\gta_sa_moddingtools\dff_convdff_librw\librwgta\tools\coltest\coltest.cpp(80): warning C4060: switch-statement contains neither  "case"- nor "default"...

**Comment by aap** [comment]
I would guess you're trying to compile two diiferent configurations. I looks like you want to convert dffs, so I would suggest you try win-x86-null on either Release or Debug.
And yes, there are many warnings generated, most of them don't are irrelevant.

**Comment by aap** [comment]
hm, the code isn't always tested and compiled for every config. You can probably remove the assert, the struct should be correct.
And paths are hard :/ I do want to support them, but I'm not currently working on it.

**Comment by goodidea82** [comment]
Thanks
